"""actualización de modelos

Revision ID: 1163a55c5fbf
Revises: 88d29f0c024b
Create Date: 2026-04-27 16:28:08.550983

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1163a55c5fbf'
down_revision = '88d29f0c024b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Primero agregar la columna codigo a productos
    op.add_column('productos', sa.Column('codigo', sa.String(), nullable=True))
    # Generar códigos únicos para productos existentes
    op.execute("UPDATE productos SET codigo = 'PROD-' || id::text WHERE codigo IS NULL")
    op.alter_column('productos', 'codigo', nullable=False)
    op.create_unique_constraint(None, 'productos', ['codigo'])

    # Luego actualizar detalle_ventas
    op.add_column('detalle_ventas', sa.Column('producto_codigo', sa.String(), nullable=True))
    # Migrar datos: usar el código del producto basado en producto_id
    op.execute("""
        UPDATE detalle_ventas 
        SET producto_codigo = productos.codigo 
        FROM productos 
        WHERE detalle_ventas.producto_id = productos.id
    """)
    op.alter_column('detalle_ventas', 'producto_codigo', nullable=False)
    op.drop_constraint('detalle_ventas_producto_id_fkey', 'detalle_ventas', type_='foreignkey')
    op.create_foreign_key(None, 'detalle_ventas', 'productos', ['producto_codigo'], ['codigo'])
    op.drop_column('detalle_ventas', 'producto_id')

    # Finalmente actualizar ventas
    op.add_column('ventas', sa.Column('codigo_producto', sa.String(), nullable=True))
    # Migrar datos: usar el código del producto basado en producto_id
    op.execute("""
        UPDATE ventas 
        SET codigo_producto = productos.codigo 
        FROM productos 
        WHERE ventas.producto_id = productos.id
    """)
    op.alter_column('ventas', 'codigo_producto', nullable=False)
    op.drop_constraint('ventas_producto_id_fkey', 'ventas', type_='foreignkey')
    op.create_foreign_key(None, 'ventas', 'productos', ['codigo_producto'], ['codigo'])
    op.drop_column('ventas', 'producto_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Primero revertir ventas
    op.add_column('ventas', sa.Column('producto_id', sa.INTEGER(), autoincrement=False, nullable=True))
    # Migrar datos: obtener id del producto basado en codigo
    op.execute("""
        UPDATE ventas 
        SET producto_id = productos.id 
        FROM productos 
        WHERE ventas.codigo_producto = productos.codigo
    """)
    op.alter_column('ventas', 'producto_id', nullable=False)
    op.drop_constraint(None, 'ventas', type_='foreignkey')
    op.create_foreign_key('ventas_producto_id_fkey', 'ventas', 'productos', ['producto_id'], ['id'])
    op.drop_column('ventas', 'codigo_producto')

    # Luego revertir detalle_ventas
    op.add_column('detalle_ventas', sa.Column('producto_id', sa.INTEGER(), autoincrement=False, nullable=True))
    # Migrar datos: obtener id del producto basado en codigo
    op.execute("""
        UPDATE detalle_ventas 
        SET producto_id = productos.id 
        FROM productos 
        WHERE detalle_ventas.producto_codigo = productos.codigo
    """)
    op.alter_column('detalle_ventas', 'producto_id', nullable=False)
    op.drop_constraint(None, 'detalle_ventas', type_='foreignkey')
    op.create_foreign_key('detalle_ventas_producto_id_fkey', 'detalle_ventas', 'productos', ['producto_id'], ['id'])
    op.drop_column('detalle_ventas', 'producto_codigo')

    # Finalmente eliminar codigo de productos
    op.drop_constraint(None, 'productos', type_='unique')
    op.drop_column('productos', 'codigo')

    # ### end Alembic commands ###
