"""actualización de modelos

Revision ID: 22d26bc63f49
Revises: 1163a55c5fbf
Create Date: 2026-05-01 17:22:08.289080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22d26bc63f49'
down_revision = '1163a55c5fbf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['nombre'])

    with op.batch_alter_table('ventas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('precio_producto', sa.Float(), nullable=False))
        batch_op.drop_column('Valor_unit')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ventas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Valor_unit', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
        batch_op.drop_column('precio_producto')

    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
