"""init

Revision ID: 9fc1273502c1
Revises: 22d26bc63f49
Create Date: 2026-05-01 22:22:38.367295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fc1273502c1'
down_revision = '22d26bc63f49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('detalle_ventas', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('detalle_ventas_producto_codigo_fkey'), type_='foreignkey')

    with op.batch_alter_table('ventas', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('ventas_codigo_producto_fkey'), type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ventas', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('ventas_codigo_producto_fkey'), 'productos', ['codigo_producto'], ['codigo'])

    with op.batch_alter_table('detalle_ventas', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('detalle_ventas_producto_codigo_fkey'), 'productos', ['producto_codigo'], ['codigo'])

    # ### end Alembic commands ###
